spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.122/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:\masterSpring\code\sell\相关文档\日志信息\sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
    mpAppId: wxd898fcb01713c658
    mpAppSecret:
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: D:\masterSpring\code\sell
    notifyUrl: http://sellshou.natapp1.cc