spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.122/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:\masterSpring\code\sell\相关文档\日志信息\sell.log
#  level:
#    com.imooc.LoggerTest: debug